fix: Refactor global variables
It's not possible to migrate away from `@import` because:

```
pnpx sass-migrator module --migrate-deps addon/styles/addon.scss

...

Error: This stylesheet was loaded by a nested import in addon/styles/addon.scss. The module system only supports loading nested CSS using the load-css() mixin, which doesn't allow access to variables from the outer stylesheet.
  ╷
2 │   width: calc(((100% - #{$site-container}) / 2) + 14rem);
  │                          ^^^^^^^^^^^^^^^
  ╵
  addon/styles/components/_docs-viewer-x-current-page-index.scss 2:26  root stylesheet
```